### ISSUE TITLE
Succeeded to deploy RDSInstance, but failed for reconciling

### ISSUE THREAD

**Issue by zzxwill** [crossplane/provider-alibaba#65]
### What happened?

Applying the following RDSInstance yaml.
```
apiVersion: database.alibaba.crossplane.io/v1alpha1
kind: RDSInstance
metadata:
  name: poc
  labels:
    example: "true"
    engine: mysql
spec:
  forProvider:
    engine: mysql
    engineVersion: "8.0"
    dbInstanceClass: "rds.mysql.c1.large"
    dbInstanceStorageInGB: 20
    securityIPList: "0.0.0.0/0"
    masterUsername: "oam-dev"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-rds-2
  providerConfigRef:
    name: default
  deletionPolicy: Delete
```
Alibaba cloud resource mysql db is successfully created, but the reconciling failed during to the following issue.

```
➜  /Users/zhouzhengxi/Downloads k get rdsinstance
NAME           READY   SYNCED   STATE     ENGINE   VERSION   AGE
poc            True    False    Running   mysql    8.0       4m24s
```

```shell
2021-03-20T17:56:34.331+0800	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"RDSInstance","name":"poc","uid":"6e74fad2-ce0f-4ee6-b394-2367e11e5c39","apiVersion":"database.alibaba.crossplane.io/v1alpha1","resourceVersion":"18463048"}, "reason": "CannotObserveExternalResource", "message": "cannot create RDS database account: SDK.ServerError\nErrorCode: InvalidAccountName.Malformed\nRecommend: https://error-center.aliyun.com/status/search?Keyword=InvalidAccountName.Malformed&source=PopGw\nRequestId: 04A612C0-5A37-4F3D-95C0-2EAD856F9E2A\nMessage: The specified parameter \"AccountName\" is not valid."}

```

The result between Crossplane provider and Alibaba cloud resource should be consistent.

### How can we reproduce it?

Apply the template above.

### What environment did it happen in?
Crossplane version: 
v0.12.0

* Cloud provider or hardware configuration
Alibaba
* Kubernetes version (use `kubectl version`)
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
ACK
* OS (e.g. from /etc/os-release)
NA
* Kernel (e.g. `uname -a`)
NA
